name = "FilePathsBase"
uuid = "48062228-2e41-5def-b9a4-89aafe57970f"
authors = ["Rory Finnegan"]
version = "0.9.24"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[weakdeps]
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
FilePathsBaseMmapExt = "Mmap"
FilePathsBaseTestExt = "Test"

[compat]
julia = "1"
Mmap = "<0.0.1, 1"
Compat = "3.33, 4"

[extras]
JLSO = "9da8a3cd-07a3-59c0-a743-3fdc52c30d11"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"

[targets]
test = ["JLSO", "Mmap", "Test"]
